### ISSUE TITLE
Control pipeline filter string parameters are sent with additional quoation marks.

### ISSUE THREAD

**Issue by jude-adam** [fledge-iot/fledge-service-dispatcher#44]
In this example we send an IEC104Command from a 104 north plugin to a 104 south plugin, the command has these parameters : "co_type", "co_ca", "co_ioa", "co_cot", "co_negative", "co_se", "co_test", "co_ts", "co_value".

"co_type" is a string parameter , when converting the value, the resulting parameter is correct:
`
Nov 6 15:37:00 GRIDCORE-002 Fledge dispatcher[2726]: DEBUG: Result of filtering control request is {"asset_code":"IEC104Command","user_ts":"2023-11-06 15:37:00.347634+00:00","ts":"2023-11-06 15:37:00.347634+00:00","reading":{"co_type":"C_SC_NA_1","co_ca":1,"co_ioa":113,"co_cot":7,"co_negative":0,"co_se":0,"co_test":0,"co_ts":0,"co_value":1}} 
`
 however when it's received in the south it has additional quotation marks, these quotation marks have to be removed in the south plugin in order to use the parameter
 
 `
 Nov 6 15:37:00 GRIDCORE-002 Fledge iec104south[1392]: INFO: iec104 - IEC104::operation - Received operation: {type: "IEC104Command", nbParams=9, names=["co_type", "co_ca", "co_ioa", "co_cot", "co_negative", "co_se", "co_test", "co_ts", "co_value"], parameters=[""C_SC_NA_1"", "1", "113", "7", "0", "0", "0", "0", "1"]} 
 `
 
 Is this intentional?

**Comment by MarkRiddoch** [comment]
This is not intentional. FOGL-8266 has been created to resolve this.

**Comment by aklira** [comment]
Test OK, issue can closed

**Comment by FlorentP42** [comment]
This seems to be fixed in Fledge 2.3.0-73
