### ISSUE TITLE
Control pipelines: Filter order is randomized at creation

### ISSUE THREAD

**Issue by FlorentP42** [fledge-iot/fledge-service-dispatcher#53]
**Describe the bug**
When creating a control pipeline, the order of the filters is not always respected (sometimes order gets inverted).

**To Reproduce**
1. Create a north service.
3. Create a south service.
4. Create a control pipeline between those services with two filters FilterA and FilterB.
5. Verify the order of the filters displayed in the GUi (expected: FilterA, FilterB).
6. Delete the pipeline above.
7. Repeat steps from step 4 about 10 times.
8. Notice that sometimes, the pipeline is created with the filters put in the wrong order (FilterB, FilterA).

**Expected behavior**
The filters in a control pipeline are always respecting the order provided at creation.

**Additional context**
N/A

**Comment by FlorentP42** [comment]
Tested on Fledge 2.3.0-47, now they appear to be always in alphabetic order, which is also wrong as they do not respect the order provided at creation : 
![image](https://github.com/fledge-iot/fledge-service-dispatcher/assets/45787476/1c46f513-5194-491a-ab22-08a6e3fe92d0)
Produces :
![image](https://github.com/fledge-iot/fledge-service-dispatcher/assets/45787476/fbe6844f-b81f-4fb9-9ef9-162b00ffa4ff)
Filter order should be `aaa4, aaa3`

**Comment by MarkRiddoch** [comment]
The issue has been identified and a fix is currently in testing for this.

**Comment by ashish-jabble** [comment]
@FlorentP42 Thanks for the confirmation. 
> Was the fix mentionned above included in that nightly?

yes nightly on fledge repository.
The issue at Fledge Admin Control pipeline API as it was not preserving the filter order. That also means no fix for this repository.

**Comment by MarkRiddoch** [comment]
The fix for this is now in the  develop branch
