### ISSUE TITLE
 Control pipelines: Cannot update filter configuration

### ISSUE THREAD

**Issue by FlorentP42** [fledge-iot/fledge-service-dispatcher#61]
**Describe the bug**
When a control pipeline with a filter is created, changing the configuration of said filter does not work (the new configuration appears in the GUI, but is not actually used by the filter).

**To Reproduce**
1. Create a north service.
2. Create a south service.
3. Create a filter "FilterA" with a string parameter "config" (default value "DEFAULT") that prints the content of "config" every time a reading enters the filter and forwards the reading unchanged. Also add a log in the `plugin_reconfigure()` method.
4. Create a control pipeline between those services with FilterA in the list of filters.
5. Update the "config" parameter of FilterA in the control pipeline options with the value "UPDATED".
6. Notice that the log from  `plugin_reconfigure()` never appears after step 5 was executed.
7. Call a command from the north plugin so that FilterA processes it.
8. Notice the FilterA still prints "DEFAULT" and not "UPDATED".

**Expected behavior**
Updating the configuration of a filter part of a control pipeline is actually taken into account by said filter.

**Additional context**
Note that configuring FilterA through scripted API calls right after it is created and before it is provided to the control pipeline allows to give it a custom configuration once. Yet it is still impossible to update that configuration after the pipeline creation.

**Comment by FlorentP42** [comment]
Something seems to have changed about this issue in Fledge 2.3.0: Now the reconfigure function on the filter is called but it is called in a loop infinitely after making a single config change:
![image](https://github.com/fledge-iot/fledge-service-dispatcher/assets/45787476/f2a7bab4-8592-496e-ad3a-7d96167c0961)

**Comment by FlorentP42** [comment]
Tested on Fledge 2.3.0-47 nightly, now the observed behavior is as follow:

- Update the pipeline filter configuration.
- A log indicating that `plugin_reconfigure()` was called is printed once.
- Call an operation from the north plugin.
- The value printed by the periodic log is still "DEFAULT" which means that either:
  - `plugin_reconfigure()` is called on a filter which is not the one actually being used by the control pipeline.
  - The `newConfig` parameter of `plugin_reconfigure()` does not contain the new configuration but the one provided at pipeline creation.

NB: Adding a Fledge restart after updating the filter configuration does not help either.

**Comment by MarkRiddoch** [comment]
It looks like the merge of the fix lost a line of code. This has now be reinstated and has resolved the issue with the repeated logs. This will appear in the next night build. Apologies for this merge issue.

**Comment by FlorentP42** [comment]
Tested on Fledge 2.3.0-73, this issue seems to be fixed completely in that nightly :)
